# Generated by Django 3.2.7 on 2022-04-21 02:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_match_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
