# Generated by Django 3.2.7 on 2022-02-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_sessioncookie'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioncookie',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
