# Generated by Django 3.2.7 on 2022-05-03 01:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_match_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
