# Generated by Django 3.2.7 on 2022-05-24 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_match_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_match_in_progress',
            field=models.BooleanField(default=True),
        ),
    ]
